project_id = "gbdupuiartcxjkjxkxiz"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.ai-ocr]
verify_jwt = false

[functions.google-drive-config]
verify_jwt = false

[functions.google-drive-ocr]
verify_jwt = false

[functions.sop-ocr]
verify_jwt = false

[functions.mold-ocr]
verify_jwt = false
